"""Tool definitions; device addresses come from environment configuration."""
from typing import Any, Dict, List


TOOLS: List[Dict[str, Any]] = [
    {
        "id": "x_nav",
        "name": "底盘导航兼容 API",
        "description": "兼容既有作业平台导航接口并转发至 18083",
        "location": "body",
        "port": 9000,
        "path": "/",
        "health_path": "/api/health",
        "probe_timeout": 4.0,
        "kind": "api",
        "details_adapter": "x_nav",
    },
    {
        "id": "suction",
        "name": "吸盘控制台",
        "description": "EVS01 / ES80Z 状态、吸取、停止和反吹释放",
        "location": "body",
        "port": 18080,
        "path": "/",
        "health_path": "/api/v1/health",
        "kind": "frontend",
        "details_adapter": "suction",
    },
    {
        "id": "yolo",
        "name": "YOLO 调试",
        "description": "模型、标签、相机参数、烟盒信息和坐标结果",
        "location": "body",
        "port": 18081,
        "path": "/debug",
        "health_path": "/health",
        "kind": "frontend",
        "details_adapter": "yolo",
    },
    {
        "id": "slam",
        "name": "底盘与动作链",
        "description": "SLAM、传感器、导航、点位库和动作编排",
        "location": "body",
        "port": 18083,
        "path": "/",
        "health_path": "/api/health",
        "kind": "frontend",
        "details_adapter": "slam",
    },
    {
        "id": "visualizer",
        "name": "3D 相对位置",
        "description": "G1-D、相机、烟盒位置和算法结果展示",
        "location": "body",
        "port": 18085,
        "path": "/",
        "health_path": "/",
        "kind": "frontend",
    },
    {
        "id": "remote",
        "name": "遥控面板",
        "description": "底盘与立柱的手动调试入口",
        "location": "body",
        "port": 18086,
        "path": "/",
        "health_path": "/",
        "kind": "frontend",
    },
    {
        "id": "arm_console",
        "name": "机械臂任务控制台",
        "description": "抓取、放置、复位、急停和任务日志",
        "location": "box",
        "port": 18090,
        "path": "/",
        "health_path": "/api/health",
        "kind": "frontend",
        "details_adapter": "arm_console",
    },
    {
        "id": "arm_ik",
        "name": "机械臂联合 IK",
        "description": "腰部与右臂联合逆解、连续抓取轨迹及任务执行状态",
        "location": "box",
        "port": 18090,
        "path": "/",
        "health_path": "/api/state",
        "kind": "runtime",
        "details_adapter": "arm_ik",
    },
    {
        "id": "control_api",
        "name": "G1-D 控制 API",
        "description": "底盘、立柱、机械臂与导航的聚合状态",
        "location": "box",
        "port": 28090,
        "path": "/",
        "health_path": "/health",
        "kind": "frontend",
    },
    {
        "id": "pose_adjust",
        "name": "位置微调服务",
        "description": "烟盒位置微调、右手安全入位规划与执行 API",
        "location": "body",
        "port": 18084,
        "path": "/health",
        "health_path": "/health",
        "kind": "api",
        "details_adapter": "pose_adjust",
    },
    {
        "id": "lift_height",
        "name": "立柱高度服务",
        "description": "真实物理高度、开机最低点与偏移标定 API",
        "location": "body",
        "port": 28089,
        "path": "/api/offset",
        "health_path": "/api/basic_status",
        "kind": "api",
        "details_adapter": "lift_height",
    },
    {
        "id": "arm_relay",
        "name": "机械臂命令转发",
        "description": "机械臂 ROS2 Topic 的 HTTP 转发服务",
        "location": "box",
        "port": 18088,
        "path": "/",
        "health_path": "/",
        "kind": "api",
        "details_adapter": "arm_relay",
    },
    {
        "id": "es80z_backend",
        "name": "ES80Z RS485 后端",
        "description": "串口、Modbus RTU 与吸盘状态服务",
        "location": "box",
        "port": 18089,
        "path": "/api/v1/health",
        "health_path": "/api/v1/health",
        "kind": "api",
        "details_adapter": "suction",
    },
]
